config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'auths#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'auths#destroy', as: 'signout', via: [:get, :post]

  root "users#first", as: :first
  
  get 'users' => 'users#index'
  get 'signup' => "users#new", as: :sign_up
  post 'users' => 'users#create'
  get 'users/:id' => 'users#show', as: :user 
  get 'users/:id/edit' => 'users#edit', as: :edit_user 
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy', as: :delete_user
  
  post 'signup' => 'users#create'
  
  get 'signin' => 'sessions#new', as: :sign_in
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy', as: :sign_out
  resources :sessions, only: [:new, :create, :destroy]

  get 'jobs/results' => 'jobs#show', as: :show_job
  get 'jobs/search' => 'jobs#edit', as: :edit_job
  resources :jobs, only: [:index, :update]

  resources :profiles, only: [:index]
  get 'profiles/:name' => 'profiles#show', as: :profile
 

  resources :tests, only: [:index, :update]

  
  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
BASE_URI = "http://tech-profiles.herokuapp.com/profiles/"
END_URI = ".json"

	def search name
		uri = BASE_URI + name.gsub(' ','+').gsub('/','%2F') + END_URI
		@response = HTTParty.get uri
		return @response
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	def index
    	@profiles = Profile.all
    	fill_if_empty
    	if signed_in?
    		@response = HTTParty.get "http://tech-profiles.herokuapp.com/profiles.json"
		else
			render 'users/first'
		end
	end

	def show
		fill_if_empty
		if signed_in?
  			@profile = Profile.first.search(params[:name])
  		else
  			render 'users/first'
  		end
	end

	private
		def fill_if_empty
			if Profile.first.nil?
				Profile.create
			end
		end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/index.html.erb
<% @response.each do |r| %>
<div class="result">
<%= link_to "Link", profile_path(r["name"]) %>
<h3><%= r["name"] %></h3>
<h4><%= r["description"] %></h4>
<h4><%= r["salary"] %></h4>
<br>
</div>
<% end %>

app/views/profiles/show.html.erb
<div class="result">
<h3><%= @profile["name"].upcase %></h3>
<h4><%= @profile["description"] %></h4>
<h4><%= @profile["salary"] %></h4>
<br>

<%= link_to "Look For #{@profile['name']} Job Openings", jobs_path(@profile["name"]), class: "btn btn-default" %>
<%= link_to "Browse Other Tech Positions", profiles_path, class: "btn btn-default" %>

</div>