config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'auths#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'auths#destroy', as: 'signout', via: [:get, :post]

  root "users#first", as: :first
  
  get 'users' => 'users#index'
  get 'signup' => "users#new", as: :sign_up
  post 'users' => 'users#create'
  get 'users/:id' => 'users#show', as: :user 
  get 'users/:id/edit' => 'users#edit', as: :edit_user 
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy', as: :delete_user
  
  post 'signup' => 'users#create'
  
  get 'signin' => 'sessions#new', as: :sign_in
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy', as: :sign_out
  resources :sessions, only: [:new, :create, :destroy]

  get 'jobs/results' => 'jobs#show', as: :show_job
  get 'jobs/search' => 'jobs#edit', as: :edit_job
  resources :jobs, only: [:index, :update]

  resources :profiles, only: [:index]
  get 'profiles/:name' => 'profiles#show', as: :profile
 

  resources :tests, only: [:index, :update]

  
  

end

app/models/job.rb
class Job < ActiveRecord::Base
BASE_URI = "http://service.dice.com/api/rest/jobsearch/v1/simple.json?text="

	def search_index
		uri = BASE_URI
		@response = HTTParty.get uri
		return @response
	end

	def adv_search
		uri = BASE_URI + title.gsub(' ','+') + "&state=" + state.gsub(' ','+') + "&city=" + zip.gsub(' ','+')
		puts uri
		@response = HTTParty.get uri
		return @response
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    if signed_in?
      fill_if_empty
      @job = Job.first
      if params[:format]
        @job.update_attributes(title: params[:format])
        @response = @job.adv_search
      else
        @response = @job.search_index
      end
    else
      render 'users/first'
    end
  end

  def show
    if signed_in?
      fill_if_empty
      @job = Job.first
      @response = @job.adv_search
    else
      render 'users/first'
    end
  end

  def edit
  	if signed_in?
      fill_if_empty
  		@job = Job.first
  	else
  		render 'users/first'
  	end
  end

  def update
    if signed_in?
      fill_if_empty
      @job = Job.first
      
      if @job.update_attributes(job_params)
        redirect_to show_job_path
      else
        redirect_to 'edit'
      end
    else
      render 'users/first'
    end
  end

  private
    def job_params
      params.require(:job).permit(:title, :state, :zip)
    end

    def fill_if_empty
      if Job.first.nil?
        Job.create(title:"", state:"", zip:"")
      end
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_results.html.erb
<div class="jobResults">
	<%= render "search" %>
	<%= link_to "Advanced Search", edit_job_path %>

	<% @response["resultItemList"].each do |r| %>
	<div class="result">
	<h3><%= r["jobTitle"].upcase %></h3>
	<h4><%= r["location"].upcase %></h4>
	<h4><%= r["detailUrl"] %></h4>
	<h4><%= r["company"] %></h4>
	<h4><%= r["date"] %></h4>
	<br>
	</div>
	<% end %>
</div>

app/views/jobs/_search.html.erb
<%= form_for @job do |f| %>

	<p>Search by Job Title: <%= f.text_field :title, :value => "" %></p>
	<%= f.hidden_field :state, :value => "" %>
	<%= f.hidden_field :zip, :value => "" %>
	
	<%= f.submit "Search" %>
<% end %>

app/views/jobs/edit.html.erb
<%= form_for @job do |f| %>
	<h1>Advanced Search</h1>
	<p>Job Title: <%= f.text_field :title, value: "" %></p>
	<p>State: <%= f.text_field :state, value: "" %></p>
	<p>Zip Code: <%= f.text_field :zip, value: "" %></p>
	<%= f.submit "Search" %>
<% end %>

app/views/jobs/index.html.erb
<%= render "results" %>

app/views/jobs/show.html.erb
<%= link_to "Clear Search Results", jobs_path %>
<%= render "results" %>