config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'auths#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'auths#destroy', as: 'signout', via: [:get, :post]

  root "users#first", as: :first
  
  get 'users' => 'users#index'
  get 'signup' => "users#new", as: :sign_up
  post 'users' => 'users#create'
  get 'users/:id' => 'users#show', as: :user 
  get 'users/:id/edit' => 'users#edit', as: :edit_user 
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy', as: :delete_user
  
  post 'signup' => 'users#create'
  
  get 'signin' => 'sessions#new', as: :sign_in
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy', as: :sign_out
  resources :sessions, only: [:new, :create, :destroy]

  get 'jobs/results' => 'jobs#show', as: :show_job
  get 'jobs/search' => 'jobs#edit', as: :edit_job
  resources :jobs, only: [:index, :update]

  resources :profiles, only: [:index]
  get 'profiles/:name' => 'profiles#show', as: :profile
 

  resources :tests, only: [:index, :update]

  
  

end

app/models/user.rb
class User < ActiveRecord::Base

# Constant that validates for email @ and .com
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i

	before_save {self.email = email.downcase}
	validates :name, presence: true

	# Validates for email being filled
	validates :email, presence: true,
			format: { with: VALID_EMAIL_REGEX },
			uniqueness: { case_sensitive: false }

	# Validates password

	has_secure_password
	validates :password_digest, presence: true 
	validates :password_digest, length: {minimum: 6}


	# before_create :create_remember_token

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end
# # ////// Facebook ////
	def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.info = auth
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.password_digest = "facebook" 
    user.email = auth.info.email
    user.save!
  end
end
# ///// End Facebook ////
	private 
		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :find_user, only: [:show, :edit, :update, :destroy]
before_action :signed_in_user, only: [:index, :show, :edit, :update, :destroy]
before_action :correct_user, only: [:show, :edit, :update, :destroy, :index]

def first
	if signed_in?
		redirect_to new_session_path
	end
end

def index
	@users = User.all
end

def show
end 

def new
	if current_user
		redirect_to current_user
	else 
		@user = User.new
	end
end

def create
	@user = User.new(user_params)

	  if @user.save
	  	UserMailer.welcome_email(@user.email).deliver
	    sign_in @user
	    redirect_to @user
	  else
	     render :new 
	  end
end

def edit
	@user = User.find(params[:id])
end

def update
	if @user.update_attributes(user_params)
		redirect_to @user
	else
		render 'edit'
	end
end

def destroy
	if @user.destroy
		render 'users/first'
	else
		render 'show'
	end
end


private
  	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
		
	def find_user
		@user = User.find(params[:id])
	end

	def correct_user
		find_user
		if fb_signin?
			redirect_to(current_userf) unless current_userf?(@user)
		else
			redirect_to(current_user) unless current_user?(@user)
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
<%=f.label:password_confirmation %><br>
<%=f.text_field:password_confirmation %>
</div>

app/views/users/edit.html.erb
<link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>

<div class="row">

<div class="span6 offset3">
  <%= form_for @user do |f| %>
  <% if @user.errors.any? %>

<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

<ul>
  <% @user.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
</div>
  <% end %>
<div class="firstShow">      
<div id="block">
      <div class="center">
      <p><%= f.label :name %><p>
      <p class="new_input"><%= f.text_field :name %><br/></p>
      <p><%= f.label :email %></p>
      <p class="new_input"><%= f.text_field :email %><br/></p>
      <p><%= f.label :password %></p>
      <p class="new_input"><%= f.password_field :password %><br/></p>
      <p><%= f.label :password_confirmation %></p>
      <p class="new_input"><%= f.password_field :password_confirmation %><br/></p>
      <p><%= f.submit "Update", class: "btn btn-large btn-primary" %></p>

      </div>
    <% end %>

    <div class="center"> <%= link_to "Or Go Back", @user %> </div>
  </div>
</div>
</div>
</div>

app/views/users/first.html.erb
<div class="firstShow">
		<div id="block">
      <div id="title">
  		<h1><b>Tech.Match</b></h1>
      </div>   
		<p>
		Log into Tech.Match
		</p>
    <div class="button1">
		  <p>
    	<%= link_to 'New Account', sign_up_path , class: "btn btn-default btn-lg btn-block" %>
  		</p>
  		<p>
    	<%= link_to 'Log In Now', sign_in_path , class: "btn btn-default btn-lg btn-block" %>
  		</p>
      </div>
  		</div>
      <hr/>
      <div id="user-widget">
  <% if current_userf %>
    Welcome <strong><%= current_userf.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>

  <% end %>
</div>
<% if current_userf %>
<br/>

  <%= image_tag current_userf.info["info"]["image"], class: "prof_pic" %>
 
<% end %>
</div>
  

app/views/users/index.html.erb
<div class="firstShow">      
<div id="block">

<h1>Hello users! Please sign in!</h1>

<title>New User Sign in</title>


<p>Already have an account? Sign in!

</div>
</div>

<table> 
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th>Remember Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.remember_token %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

  

app/views/users/new.html.erb
<link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user, url: sign_up_path) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
<div class="firstShow">      
<div id="block">
      <div class="center">
      <p><%= f.label :name %><p>
      <p class="new_input"><%= f.text_field :name %><br/></p>
      <p><%= f.label :email %></p>
      <p class="new_input"><%= f.text_field :email %><br/></p>
      <p><%= f.label :password %></p>
      <p class="new_input"><%= f.password_field :password %><br/></p>
      <p><%= f.label :password_confirmation %></p>
      <p class="new_input"><%= f.password_field :password_confirmation %><br/></p>
      <p><%= f.submit "Sign Up", class: "btn btn-large btn-primary" %></p>

      </div>
    <% end %>

    <div class="center"> <%= link_to "Or Sign In", signin_path %> </div>
  </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="firstShow">

	<p> Welcome to TECH.MATCH!!</p> 

	<h1><%= @user.email %></h1>
	<p><%= link_to "Edit", edit_user_path %></p>
	<p><%= link_to "Delete Your Account", delete_user_path, method: :delete, data: { confirm: 'Are you sure?'} %></p>
	<p><%= link_to "See Jobs Close To Me", jobs_path %></p>
	<p><%= link_to "Go To My Profile", profile_path(@user.result) %></p>
	<p><%= link_to "Sign Out", sign_out_path , method: "delete" %></p> 

</div>